// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdboy4bkeJJYJZ6lsHJMNrX4dy4dVpmDM',
    appId: '1:103663170900:web:dbe2434569a91f0fa384c1',
    messagingSenderId: '103663170900',
    projectId: 'flutter-kolkata',
    authDomain: 'flutter-kolkata.firebaseapp.com',
    storageBucket: 'flutter-kolkata.appspot.com',
    measurementId: 'G-X0Q98CP2SE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSuEAp4FatQ3Qwx-4KiDon9TcZcotI2Ag',
    appId: '1:103663170900:android:c11115df3aeebc3ba384c1',
    messagingSenderId: '103663170900',
    projectId: 'flutter-kolkata',
    storageBucket: 'flutter-kolkata.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2lyU2g5aax3uRJBuIBxAc7PBZknqyEFY',
    appId: '1:103663170900:ios:782f1b3e7106ceafa384c1',
    messagingSenderId: '103663170900',
    projectId: 'flutter-kolkata',
    storageBucket: 'flutter-kolkata.appspot.com',
    iosClientId: '103663170900-u5elvc43td3oofv062qg2dqsccg8l3da.apps.googleusercontent.com',
    iosBundleId: 'com.flutterkolkata.flutterkolkata',
  );
}
